### ISSUE TITLE
scripts doesnot work after ajaxing

### ISSUE THREAD

**Issue by sonill** [browserstate/ajaxify#17]
page ajazification works great but after ajaxification all the scripts stop working.

here is a sample code of mine
<code>
$('.browse-all-btn').on('click', function(){
    $browse.stop().slideDown();
    $(this).addClass('selected');
});
$browse.on('mouseleave', function(){
    $(this).stop().slideUp();
    $('.browse-all-btn').removeClass('selected');
});
</code>
any help to make these script work again after ajaxification will be appreciated.
thank you

**Comment by rdebeasi** [comment]
Could you please provide an example of the full page and JavaScript?

**Comment by richgcook** [comment]
I'm having a similar issue — how does one retrigger scripts on AJAX load? I have scripts (sliders etc) within the ajax'd content that don't work now. Any ideas? @rdebeasi

**Comment by rdebeasi** [comment]
Rather than initializing sliders and such right in document.ready, I usually create an initialize function for my site. I call that function on document.ready, and I also call it on the 'statechangecomplete' callback.

That would look something like this:

``` javascript
$(function() {
  function myInit() {
    // Initialize sliders and stuff in here.
  }

  // Call myInit when document is ready.
  myInit();

  // Call myInit again after each AJAX load.
  $(window).on('statechangecomplete', function() {
    myInit();
    // Optionally, do other stuff only after an AJAX load.
  });
});
```

**Comment by richgcook** [comment]
Thanks for this, @rdebeasi — guess my skills failed me here.

This worked a treat.

**Comment by rdebeasi** [comment]
Glad to hear it - you're very welcome!

**Comment by sonill** [comment]
it seems to work, thank you
