### ISSUE TITLE
Link is a porn site

### ISSUE THREAD

**Issue by uvishere** [browserstate/ajaxify#42]
the link for Andrew Rubanov's site ( http://andreyrubanov.ru/ ) in showcase is a pornsite. Please remove the url or perform the action required.

**Comment by balupton** [comment]
Thanks. Will look into whether or not it uses the script or not. If it does, I'll add a note to the readme, if it doesn't the URL will be removed. Cheers

**Comment by balupton** [comment]
Okay, seems the site's domain lapsed as is no longer what its description says it is. Here is an archive of what it was at the time: http://web.archive.org/web/20131222211326/http://andreyrubanov.ru/home/

So will remove as is no longer relevant.

**Comment by balupton** [comment]
Thanks for bringing this to my attention!

**Comment by balupton** [comment]
Removed
